Pagina_Vitario/Pagina_Vitario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('',include('Vitario.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Pagina_Vitario/Vitario/urls.py
from django.urls import path

from . import views

app_name = "Vitario"

urlpatterns = [
    path('', views.inicio, name="inicio"),

    path('loginForm/',views.loginForm, name="loginForm"),
    path('login/',views.login, name="login"),
    path('loginC/',views.loginC, name="login_cerrar"),
    
    path('usuario/', views.usuario, name="usuario"),
    path('crear_usuario/', views.usuarioFormulario, name="crear_usuario"),
    path('guardar_usuario/', views.usuarioGuardar, name="guardar_usuario"),
    path('eliminar_usuario/<int:id>',views.usuarioEliminar, name="eliminar_usuario"),
    path('editarusUario/<int:id>',views.editarUsuario, name="editar_usuario"),
    path('actualizarUsuario/',views.actualizarUsuario, name="actualizar_usuario"),
    path('BuscarUsuario/',views.usuarioBuscar, name="Buscar_usuario"),
    path('registro/',views.usuarioRegistro, name="Registro"),
    
    path('mascota/', views.mascota, name="mascota"),
    path('crear_mascota/', views.mascotaFormulario, name="crear_mascota"),
    path('guardar_mascota/', views.mascotaGuardar, name="guardar_mascota"),
    path('eliminar_mascota/<int:id>',views.mascotaEliminar, name="eliminar_mascota"),
    path('editarMascota/<int:id>',views.editarMascota, name="editar_mascota"),
    path('actualizarMascota/',views.actualizarMascota, name="actualizar_mascota"),
    path('BuscarMascota/',views.mascotaBuscar, name="Buscar_mascota"),
    
    path('producto/', views.producto, name="producto"),
    path('crear_producto/', views.productoFormulario, name="crear_producto"),
    path('guardar_producto/', views.productoGuardar, name="guardar_producto"),
    path('eliminar_producto/<int:id>',views.productoEliminar, name="eliminar_producto"),
    path('editarProducto/<int:id>',views.editarProducto, name="editar_producto"),
    path('actualizarProducto/',views.actualizarProducto, name="actualizar_producto"),
    path('BuscarProducto/',views.productoBuscar, name="Buscar_producto"),
    path('concentrado/', views.productoConcentrado, name="concentrado"),
    path('accesorio/', views.productoAccesorio, name="accesorio"),
    path('medicamento/', views.productoMedicamento, name="medicamento"),
    path('premio/', views.productoPremios, name="premio"),
    
    path('factura/', views.factura, name="factura"),
    path('crear_factura/', views.facturaFormulario, name="crear_factura"),
    path('guardar_factura/', views.facturaGuardar, name="guardar_factura"),
    path('eliminar_factura/<int:id>',views.facturaEliminar, name="eliminar_factura"),
    path('editarFactura/<int:id>',views.editarFactura, name="editar_factura"),
    path('actualizarFactura/',views.actualizarFactura, name="actualizar_factura"),
    path('BuscarFactura/',views.facturaBuscar, name="Buscar_factura"),
    
    path('servicio/', views.servicio, name="servicio"),
    path('crear_servicio/', views.servicioFormulario, name="crear_servicio"),
    path('guardar_servicio/', views.servicioGuardar, name="guardar_servicio"),
    path('eliminar_servicio/<int:id>',views.servicioEliminar, name="eliminar_servicio"),
    path('editarServicio/<int:id>',views.editarServicio, name="editar_servicio"),
    path('actualizarServicio/',views.actualizarServicio, name="actualizar_servicio"),
    path('BuscarServicio/',views.servicioBuscar, name="Buscar_servicio"),
    path('tarjeta_servicio/', views.servicioTarjetas, name="tarjetaservicio"),
    
    path('cita/', views.cita, name="cita"),
    path('crear_cita/', views.citaFormulario, name="crear_cita"),
    path('guardar_cita/', views.citaGuardar, name="guardar_cita"),
    path('eliminar_cita/<int:id>',views.citaEliminar, name="eliminar_cita"),
    path('editarCita/<int:id>',views.editarCita, name="editar_cita"),
    path('actualizarCita/',views.actualizarCita, name="actualizar_cita"),
    path('BuscarCita/',views.citaBuscar, name="Buscar_cita"),
    path('agendar/', views.Agendar, name="agendar"),
    path('veragenda/<str:fecha>/', views.verAgenda, name="veragenda"),
    path('guardaragenda/<str:fecha>/', views.guardarAgenda, name="guardaragenda"),
    path('apartarCita/', views.apartarCita, name="apartarCita"),
    path('formularioApartarCita/<int:empleado>', views.formularioApartarCitas, name="formularioApartarCita"),
    
    path('perfil/',views.perfil, name="perfil"),
    path('actualizarPerfil/',views.actualizarPerfil, name="actualizar_perfil"),
    
    path('carrito/',views.carritoCompra, name="carrito"),
    path('agregar/<int:producto_id>/',views.agregar_producto, name="agregar"),
    path('restar/<int:producto_id>/',views.restar_producto, name="restar"),
    path('limpiar/',views.limpiar_carrito, name="limpiar"),
]

Pagina_Vitario/Vitario/models.py
from email.policy import default
from django.db import models

""" Crea una clase llamada Usuario, que es un modelo y esta conectada con otras clases
    La función __str__ es una función especial que se llama cuando imprime un objeto
    :return: El nombre del objeto
"""

class Usuario (models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    telefono = models.IntegerField()
    correo = models.CharField(max_length=100)
    usuario = models.CharField(max_length=100)
    clave = models.CharField(max_length=100)
    roles = (
        ("A", "Administrador"),
        ("E", "Empleado"),
        ("C", "Cliente"),
    )
    rol = models.CharField(choices= roles, max_length=1, default="C")
    foto = models.ImageField(upload_to = 'vitario/fotos', default = 'vitario/fotos/defaultUsu.png')
    
    def __str__(self):
        return self.nombre
    
"""Crea una clase llamada Mascota que tiene un nombre, tipo, edad y usuario.
"""
class Mascota (models.Model):
    nombre_mascota =  models.CharField(max_length=100)
    tipo_mascota = models.CharField(max_length=100)
    edad = models.IntegerField()
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    
"""Crea una clase llamada Producto que tiene los siguientes atributos: codigo_producto,
    nombre_producto, cantidad, precio, categorias, categoria, and foto.
    return: el monbre del producto
"""
class Producto (models.Model):
    codigo_producto = models.IntegerField()
    nombre_producto = models.CharField(max_length=100)
    cantidad= models.IntegerField()
    precio = models.IntegerField()
    categorias = (
        ("M","Medicamentos"),
        ("A","Accesorios"),
        ("C","Concentrado"),
        ("AP","Alimentos y Premios"),
    )
    categoria = models.CharField(choices=  categorias, max_length=2)
    foto = models.ImageField(upload_to = 'vitario/fotos', default = 'vitario/fotos/defaultPro.png')

    
    def __str__(self):
        return f"{self.nombre_producto}-{self.precio}"
    
"""Crea una clase llamada Servicios que tiene el codigo, el nombre y el precio.
    return: el nombre del servicio
"""
class Servicios (models.Model):
    codigo_servicio = models.IntegerField()
    nombre_servicio = models.CharField(max_length=100)
    precio_servicio = models.IntegerField()
    foto = models.ImageField(upload_to = 'vitario/fotos', default = 'vitario/fotos/defaultMas.png')  
    
    def __str__(self):
        return self.nombre_servicio
    
"""Crea una clase llamada Factura, que es un modelo.
"""
class Factura (models.Model):
    nombre_producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
    cantidad = models.IntegerField()
    total_sin_descuento = models.IntegerField()
    descuento = models.IntegerField()
    total_con_descuento = models.IntegerField()
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    servicios = models.ForeignKey(Servicios, on_delete=models.DO_NOTHING, default = "Sin servicio")
    pagos = (
        ("E", "Efectivo"),
        ("T", "Trasnferencia"),
        ("A", "Tarjeta"),
    )
    medio_pago = models.CharField(choices=pagos, max_length=1, default="E")

class Disponibilidad(models.Model):
    empleado = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    DIAS = (
        ('L', 'Lunes'),
        ('M', 'Martes'),
        ('X', 'Miércoles'),
        ('J', 'Jueves'),
        ('V', 'Viernes'),
        ('S', 'Sábado'),
        ('D', 'Domingo'),
    )
    dia = models.CharField(max_length=1, choices=DIAS)
    HORAS = (
        (9, '9AM'),
        (10, '10AM'),
        (11, '11AM'),
        (12, '12M'),
        (13, '1PM'),
        (14, '2PM'),
        (15, '3PM'),
        (16, '4PM'),
        (17, '5PM'),
        (18, '6PM'),
        (19, '7PM'),
        (20, '8PM'),
    )
    hora = models.IntegerField(choices=HORAS)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    reservado = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.id} - {self.empleado}"
    
"""Citas es un modelo que tiene una clave externa para el usuario, un DateTimeField y una clave externa para los servicios.
"""
class Citas (models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.DO_NOTHING)
    disponibilidad= models.ForeignKey(Disponibilidad, on_delete=models.DO_NOTHING)
    ESTADO = (
        (1, 'Reservado'),
        (2, 'Cumplida'),
        (3, 'Cancelada'),
    )
    estado = models.IntegerField(choices=ESTADO)

Pagina_Vitario/Vitario/templates/Vitario/factura/crear_factura.html
{% extends 'Vitario/base.html' %}

{% block body %}

<h1>CREAR FACTURAS</h1>

<form style="text-align:center;" action="{% url 'Vitario:guardar_factura' %}" method="post">
    {% csrf_token %}

    <label for="">Nombre del producto</label><br />
    <select class="form-control" name="nombre_producto" style="width:70%; margin-left: auto; margin-right:auto;">
        {% if producto %}
            {% for registro in producto %}
                <option value="{{registro.id}}">{{registro.nombre_producto}}</option>
            {% endfor %}
        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    </select><br/>
    
    <label for="">Cantidad</label><br />
    <input type="text" class="form-control" name="cantidad" style="width:70%; margin-left: auto; margin-right:auto;"><br/>

    <label for="">total sin descuento</label><br />
    <input type="number" class="form-control" name="total_sin_descuento" style="width:70%; margin-left: auto; margin-right:auto;"><br/>

    <label for="">Descuento</label><br />
    <input type="number" class="form-control" name="descuento" style="width:70%; margin-left: auto; margin-right:auto;"><br/>

    <label for="">Total con descuento</label><br />
    <input type="number" class="form-control" name="total_con_descuento" style="width:70%; margin-left: auto; margin-right:auto;"><br/>

    <label for="">Medio de Pago</label><br />
    <select class="form-control" name="medio_pago" style="width:70%; margin-left: auto; margin-right:auto;">
        <option value="E">Efectivo</option>
        <option value="T">Transferencia</option>
        <option value="A">Tarjeta</option>
    </select><br/>

    <label for="">usuario</label><br />
    <select class="form-control" name="usuario" style="width:70%; margin-left: auto; margin-right:auto;">
        {% if usuario %}
            {% for registro in usuario %}
                <option value="{{registro.id}}">{{ registro.usuario }}</option>
            {% endfor %}
        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    </select><br/>

    <label for="">Servicios</label><br />
    <select class="form-control" name="servicio" style="width:70%; margin-left: auto; margin-right:auto;">
        {% if servicio %}
            {% for registro in servicio %}
                <option value="{{registro.id}}">{{registro.nombre_servicio}}</option>
            {% endfor %}
        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    </select><br/>

    <button type="submit" class="btn btn-primary">Guardar</button><br><br>
</form>
{% endblock  %}

Pagina_Vitario/Vitario/templates/Vitario/factura/editar_factura.html
{% extends 'Vitario/base.html' %}

{% block body %}

<h1>MODIFICAR FACTURA <strong> -_- {{ datos.id_factura }} -_-</strong></h1>

<form style="text-align:center;" action="{% url 'Vitario:actualizar_factura' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="id" value="{{datos.id}}" >
    
    <!-- <label for="">Nombre del producto</label><br />
    <select class="form-control" name="nombre_producto" style="width:70%; margin-left: auto; margin-right:auto;" value="{{ datos.nombre_producto }}">
        {% if producto %}
            {% for registro in producto %}
                <option value="{{registro.id}}">{{registro.nombre_producto}}</option>
            {% endfor %}
        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    </select><br/> -->
    
    <label for="">Cantidad</label><br />
    <input type="text" class="form-control" name="cantidad" style="width:70%; margin-left: auto; margin-right:auto;" value="{{ datos.cantidad }}"><br/>

    <label for="">total sin descuento</label><br />
    <input type="number" class="form-control" name="total_sin_descuento" style="width:70%; margin-left: auto; margin-right:auto;" value="{{ datos.total_sin_descuento }}"><br/>

    <label for="">Descuento</label><br />
    <input type="number" class="form-control" name="descuento" style="width:70%; margin-left: auto; margin-right:auto;" value="{{ datos.descuento }}"><br/>

    <label for="">Total con descuento</label><br />
    <input type="number" class="form-control" name="total_con_descuento" style="width:70%; margin-left: auto; margin-right:auto;" value="{{ datos.total_con_descuento }}"><br/>

    <label for="">Medio de Pago</label><br />
    <select class="form-control" name="medio_pago" style="width:70%; margin-left: auto; margin-right:auto; " value="{{ datos.medio_pago }}">
        <option value="E">Efectivo</option>
        <option value="T">Transferencia</option>
        <option value="A">Tarjeta</option>
    </select><br/>

    <!-- <label for="">Servicios</label><br />
    <select class="form-control" name="servicio" style="width:70%; margin-left: auto; margin-right:auto;" >
        {% if servicio %}
            {% for registro in servicio %}
                <option value="{{registro.id}}">{{registro.nombre_servicio}}</option>
            {% endfor %}
        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    </select><br/> -->

    <button type="submit" class="btn btn-primary">Guardar</button><br><br>
</form>
{% endblock  %}

Pagina_Vitario/Vitario/templates/Vitario/factura/listar_factura.html
{% extends 'Vitario/base.html' %}


{% block body %}

<h1>FACTURAS</h1>

<a class="btn btn-primary" href="{% url 'Vitario:crear_factura' %}">Nueva factura</a> <br /><br />

    
    <input class="form-control me-2" type="search" name="buscar" id="buscar" placeholder="Buscar" aria-label="Search" value="{{ Datos }}" onkeyup="buscarA('{% url 'Vitario:Buscar_factura' %}');">
    {% csrf_token %}

{%  if Datos %}
<a href="{% url 'Vitario:factura' %}"> ver todos </a>
{% endif %}

<div id="res">

{% if page_obj %}




<table border="1" width="100%" class="table">
    <thead>
        <tr>
            
            <td>Id</td>
            <td>Nombre del producto</td>
            <td>Cantidad</td>
            <td>Total sin descuento</td>
            <td>Descuento</td>
            <td>Total con descuento</td>
            <td>Pago</td>
            <td>Usuario</td>
            <td>Servicio</td>
            <td>Editar</td>
            <td>Eliminar</td>
        </tr>
    </thead>
    <tbody>

        {% for registro in page_obj %}
        <tr>
            <td>{{ registro.id }}</td>
            <td>{{ registro.nombre_producto }}</td>
            <td>{{ registro.cantidad }}</td>
            <td>{{ registro.total_sin_descuento }}</td>
            <td>{{ registro.descuento }}</td>
            <td>{{ registro.total_con_descuento }}</td>
            <td>{{ registro.get_medio_pago_display }}</td>
            <td>{{ registro.usuario }}</td>
            <td>{{ registro.servicios }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'Vitario:editar_factura' registro.id %}"> editar</a>
            </td>
            <td>
                <a class="btn btn-danger" onclick="confirmarEliminar('{% url 'Vitario:eliminar_factura' registro.id %}')";> eliminar</a>
            </td>
        </tr>
        

        {% endfor %}
    </tbody>
</table>

<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
            
            <a class="page-link" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }} " {% endif %}  >Anterior</a>
            
        </li>
        {% for i in "d"|rjust:page_obj.paginator.num_pages|make_list %}

        <li class="page-item {% if forloop.counter == page_obj.number %} active {% endif %}"><a class="page-link" aria-current="page " href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>

        {% endfor %}

        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %} ">
            <a class="page-link" {% if page_obj.has_next %} href="?page={{ page_obj.next_page_number }}" {% endif %} >siguiente</a>
        </li>
    </ul>
</nav>



{% else %}
<h1>No hay datos</h1>
{% endif %}

</div>

{% endblock %}

Pagina_Vitario/Vitario/templates/Vitario/factura/listar_factura_ajax.html
{% if page_obj %}



<table border="1" width="100%" class="table">
    <thead>
        <tr>
            
            <td>Id</td>
            <td>Nombre del producto</td>
            <td>Cantidad</td>
            <td>Total sin descuento</td>
            <td>Descuento</td>
            <td>Total con descuento</td>
            <td>Pago</td>
            <td>Usuario</td>
            <td>Servicio</td>
            <td>Editar</td>
            <td>Eliminar</td>
        </tr>
    </thead>
    <tbody>

        {% for registro in page_obj %}
        <tr>
            <td>{{ registro.id }}</td>
            <td>{{ registro.nombre_producto }}</td>
            <td>{{ registro.cantidad }}</td>
            <td>{{ registro.total_sin_descuento }}</td>
            <td>{{ registro.descuento }}</td>
            <td>{{ registro.total_con_descuento }}</td>
            <td>{{ registro.get_medio_pago_display }}</td>
            <td>{{ registro.usuario }}</td>
            <td>{{ registro.servicios }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'Vitario:editar_factura' registro.id %}"> editar</a>
            </td>
            <td>
                <a class="btn btn-danger" onclick="confirmarEliminar('{% url 'Vitario:eliminar_factura' registro.id %}')";> eliminar</a>
            </td>
        </tr>
        

        {% endfor %}
    </tbody>
</table>

<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
            
            <a class="page-link" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }} " {% endif %}  >Anterior</a>
            
        </li>
        {% for i in "d"|rjust:page_obj.paginator.num_pages|make_list %}

        <li class="page-item {% if forloop.counter == page_obj.number %} active {% endif %}"><a class="page-link" aria-current="page " href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>

        {% endfor %}

        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %} ">
            <a class="page-link" {% if page_obj.has_next %} href="?page={{ page_obj.next_page_number }}" {% endif %} >siguiente</a>
        </li>
    </ul>
</nav>



{% else %}
<h1>No hay datos</h1>
{% endif %}