Pagina_Vitario/Pagina_Vitario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('',include('Vitario.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Pagina_Vitario/Vitario/urls.py
from django.urls import path

from . import views

app_name = "Vitario"

urlpatterns = [
    path('', views.inicio, name="inicio"),

    path('loginForm/',views.loginForm, name="loginForm"),
    path('login/',views.login, name="login"),
    path('loginC/',views.loginC, name="login_cerrar"),
    
    path('usuario/', views.usuario, name="usuario"),
    path('crear_usuario/', views.usuarioFormulario, name="crear_usuario"),
    path('guardar_usuario/', views.usuarioGuardar, name="guardar_usuario"),
    path('eliminar_usuario/<int:id>',views.usuarioEliminar, name="eliminar_usuario"),
    path('editarusUario/<int:id>',views.editarUsuario, name="editar_usuario"),
    path('actualizarUsuario/',views.actualizarUsuario, name="actualizar_usuario"),
    path('BuscarUsuario/',views.usuarioBuscar, name="Buscar_usuario"),
    path('registro/',views.usuarioRegistro, name="Registro"),
    
    path('mascota/', views.mascota, name="mascota"),
    path('crear_mascota/', views.mascotaFormulario, name="crear_mascota"),
    path('guardar_mascota/', views.mascotaGuardar, name="guardar_mascota"),
    path('eliminar_mascota/<int:id>',views.mascotaEliminar, name="eliminar_mascota"),
    path('editarMascota/<int:id>',views.editarMascota, name="editar_mascota"),
    path('actualizarMascota/',views.actualizarMascota, name="actualizar_mascota"),
    path('BuscarMascota/',views.mascotaBuscar, name="Buscar_mascota"),
    
    path('producto/', views.producto, name="producto"),
    path('crear_producto/', views.productoFormulario, name="crear_producto"),
    path('guardar_producto/', views.productoGuardar, name="guardar_producto"),
    path('eliminar_producto/<int:id>',views.productoEliminar, name="eliminar_producto"),
    path('editarProducto/<int:id>',views.editarProducto, name="editar_producto"),
    path('actualizarProducto/',views.actualizarProducto, name="actualizar_producto"),
    path('BuscarProducto/',views.productoBuscar, name="Buscar_producto"),
    path('concentrado/', views.productoConcentrado, name="concentrado"),
    path('accesorio/', views.productoAccesorio, name="accesorio"),
    path('medicamento/', views.productoMedicamento, name="medicamento"),
    path('premio/', views.productoPremios, name="premio"),
    
    path('factura/', views.factura, name="factura"),
    path('crear_factura/', views.facturaFormulario, name="crear_factura"),
    path('guardar_factura/', views.facturaGuardar, name="guardar_factura"),
    path('eliminar_factura/<int:id>',views.facturaEliminar, name="eliminar_factura"),
    path('editarFactura/<int:id>',views.editarFactura, name="editar_factura"),
    path('actualizarFactura/',views.actualizarFactura, name="actualizar_factura"),
    path('BuscarFactura/',views.facturaBuscar, name="Buscar_factura"),
    
    path('servicio/', views.servicio, name="servicio"),
    path('crear_servicio/', views.servicioFormulario, name="crear_servicio"),
    path('guardar_servicio/', views.servicioGuardar, name="guardar_servicio"),
    path('eliminar_servicio/<int:id>',views.servicioEliminar, name="eliminar_servicio"),
    path('editarServicio/<int:id>',views.editarServicio, name="editar_servicio"),
    path('actualizarServicio/',views.actualizarServicio, name="actualizar_servicio"),
    path('BuscarServicio/',views.servicioBuscar, name="Buscar_servicio"),
    path('tarjeta_servicio/', views.servicioTarjetas, name="tarjetaservicio"),
    
    path('cita/', views.cita, name="cita"),
    path('crear_cita/', views.citaFormulario, name="crear_cita"),
    path('guardar_cita/', views.citaGuardar, name="guardar_cita"),
    path('eliminar_cita/<int:id>',views.citaEliminar, name="eliminar_cita"),
    path('editarCita/<int:id>',views.editarCita, name="editar_cita"),
    path('actualizarCita/',views.actualizarCita, name="actualizar_cita"),
    path('BuscarCita/',views.citaBuscar, name="Buscar_cita"),
    path('agendar/', views.Agendar, name="agendar"),
    path('veragenda/<str:fecha>/', views.verAgenda, name="veragenda"),
    path('guardaragenda/<str:fecha>/', views.guardarAgenda, name="guardaragenda"),
    path('apartarCita/', views.apartarCita, name="apartarCita"),
    path('formularioApartarCita/<int:empleado>', views.formularioApartarCitas, name="formularioApartarCita"),
    
    path('perfil/',views.perfil, name="perfil"),
    path('actualizarPerfil/',views.actualizarPerfil, name="actualizar_perfil"),
    
    path('carrito/',views.carritoCompra, name="carrito"),
    path('agregar/<int:producto_id>/',views.agregar_producto, name="agregar"),
    path('restar/<int:producto_id>/',views.restar_producto, name="restar"),
    path('limpiar/',views.limpiar_carrito, name="limpiar"),
]

Pagina_Vitario/Vitario/views.py
from pathlib import Path
from django.shortcuts import render,redirect

from Vitario.Carrito import Carrito
from .models import Usuario, Mascota, Producto, Factura, Servicios, Citas, Disponibilidad
from django.core.paginator import Paginator
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
from datetime import datetime
from .crypt_1 import claveEncriptada
from os import remove, path
BASE_DIR = Path(__file__).resolve().parent.parent

# Create your views here.
#===================================================Perfil==============================================================

"""Obtiene la identificación del usuario de la sesión, luego obtiene los datos del usuario de la base
de datos y luego los pasa a la plantilla
    :param request: El objeto de la solicitud
    :return: El perfil del usuario.
"""
def perfil(request):

    login = request.session.get('logueo', False)
    q =Usuario.objects.get(pk = login[0])
    contexto = {"perfil": q }
    return render(request,'Vitario/usuario/perfil.html',contexto)

"""Actualiza el perfil del usuario.
    :param request: El objeto de la solicitud
    :return: una redirección a la vista de perfil.
"""

def actualizarPerfil(request):

    if request.method == "POST":
        try:
            # Obtener los datos del usuario de la base de datos y actualizarlos.
            login = request.session.get('logueo', False)

            q = Usuario.objects.get(pk = login[0])

            q.nombre = request.POST["nombre"]
            q.direccion = request.POST["direccion"]
            q.telefono = request.POST["telefono"]
            q.correo = request.POST["correo"]

            if q.usuario != request.POST["usuario"]:
                try:
                    consulta = Usuario.objects.get(usuario = request.POST["usuario"])
                    raise Exception("El usuario ya existe")
                except Usuario.DoesNotExist:
                    q.usuario = request.POST["usuario"]
            else:
                q.usuario = request.POST["usuario"]

            if request.POST["clave"] != "":
                q.clave = claveEncriptada(request.POST["clave"])

            q.save()
            login[1] = q.nombre
            request.session["logueo"] = login

            messages.success(request,"Actualizacion correcta")
        except Usuario.DoesNotExist:
            messages.error(request,'No existe el usuario')
        except Exception as e:
            messages.error(request, f"Error: {e}")
    else:
        messages.warning(request, "No envio datos...")

    return redirect('Vitario:perfil')

#=======================================================================================================================

"""Toma una solicitud y devuelve una respuesta.
    :param request: El objeto de solicitud es un objeto HttpRequest.
    :return: La función de renderizado está siendo devuelta.
"""

def inicio(request):
    return render(request, 'Vitario/index.html')

#====================================================LOGIN==============================================================

def loginForm(request):
    return render(request,'Vitario/login/login.html')

"""En esta funcion nos permite saber i el usuario existe y si existe que inicie sesión y rediríjalo a la página de 
inicio. y si no existe rediríjalos a la página de inicio de sesión.   
    :param request: El objeto de la solicitud
    :return: El usuario está siendo devuelto.
"""

def login(request):
        
    try:
        
        user = request.POST['usuario']
        pasw = claveEncriptada(request.POST["clave"])

        q = Usuario.objects.get(usuario = user, clave = pasw)
        
        request.session["logueo"] = [q.id, q.nombre, q.rol, q.get_rol_display()]
        messages.success(request,"Bienvenido!!")
        return redirect('Vitario:inicio')
    except:
        messages.warning(request,"Hay que ingresar los datos")
        return redirect('Vitario:inicio')   

"""Esta funcion elimina la variable de sesión "Cierra la sesión" y redirige a la página de inicio
    :param request: El objeto de la solicitud
    :return: la función de redirección.
"""

def loginC(request):

    try:
        del request.session["logueo"]
        messages.success(request, "Session cerrada")
    except Exception as e:
        messages.warning(request, "Ocurrio un error: ", e)
    return redirect('Vitario:inicio')

#=======================================================================================================================

# ===============================================USUARIOS===============================================================

"""Esta funcion consulta si el usuario ha iniciado sesión y es administrador o empleado y que muestre la lista 
de usuarios. Si el usuario no ha iniciado sesión o no es administrador o empleado, se le redirige a la página de inicio 
de sesión.
    :param request: El objeto de la solicitud
    :return:un objeto de renderizado.
"""

def usuario(request):
    
    login = request.session.get('logueo',False)
    if login and (login[3] == "Administrador" or login[3] == "Empleado"):
        q = Usuario.objects.all()
        
        p = Paginator(q, 9)
        p_number = request.GET.get('page')
        
        q = p.get_page(p_number)
        
        contexto = {'page_obj': q}
        
        return render(request, 'Vitario/usuario/listar_usuario.html', contexto)

    else:
        if login and login[3] != "Administrador" and login[3] != "Empleado":
            messages.warning(request, "usted no esta autorizados para este modulo")
            return redirect('Vitario:inicio')
        else:    
            messages.warning(request, "No has iniciado session")
            return redirect('Vitario:loginForm')

"""Si la solicitud es una solicitud POST, filtre el modelo Usuario por el término de búsqueda, pagine
    los resultados y represente los resultados en una plantilla
    
    :param request: El objeto de la solicitud
    :return: una representación de la plantilla 'Vitary/users/list_users_ajax.html'
"""
def usuarioBuscar (request):
    
    if request.method == "POST":
        q = Usuario.objects.filter(
            Q(nombre__icontains = request.POST["buscar"])|
            Q(usuario__icontains = request.POST["buscar"])
            )
        p = Paginator(q, 9)
        p_number = request.GET.get('page')
        
        q = p.get_page(p_number)
        
        contexto = {'page_obj': q, 'Datos': request.POST["buscar"]}
        
        return render(request, 'Vitario/usuario/listar_usuario_ajax.html',contexto)
    else:
        messages.warning(request, "No se han enviado datos")
        return redirect('Vitario:usuario')
    
"""Representa la plantilla y la devuelve
    :param request: El objeto de la solicitud
    :return: La función de renderizado está siendo devuelta.
"""
def usuarioFormulario(request):
    return render(request, 'Vitario/usuario/crear_usuario.html')

"""Si el método de solicitud es POST, guarde el archivo en el servidor; de lo contrario, establezca el
    archivo en la imagen predeterminada
    :param request: El objeto de la solicitud
    :return: una redirección a la url Vitario:usuario.
"""
def usuarioGuardar(request):
    try:
        if request.method == "POST":
                # Guardando la imagen en el servidor.
            if request.FILES:
                # crear instacian de file sistem storage
                fss = FileSystemStorage()
                # capturar foto de formulario
                r = request.FILES["foto"]
                # cargar archivo alservidor
                file = fss.save("vitario/fotos/"+ r.name, r)
            else:
                file = "vitario/fotos/defaultUsu.png"
            
            q = Usuario(
                nombre = request.POST["nombre"],
                direccion = request.POST["direccion"],
                telefono = request.POST["telefono"],
                correo = request.POST["correo"],
                usuario = request.POST["usuario"],
                clave = claveEncriptada(request.POST["clave"]),
                rol = request.POST["rol"],
                foto = file
            )
            q.save()
            messages.success(request,"¡Usuario guardado correctamente!")
            return redirect('Vitario:usuario')
        else:
            messages.warning(request, "¡No se han enviado datos!")
            return redirect('Vitario:usuario')
    except Exception as e:
        messages.error(request,"Error" + str(e))
        return redirect('Vitario:usuario')
    
"""Elimina un usuario de la base de datos y elimina la foto del usuario del servidor
    :param request: El objeto de la solicitud
    :param id: El id del objeto que se va a eliminar
    :return: una redirección a la url vitarium:usuario.
"""
def usuarioEliminar(request,id):
    try:
        a = Usuario.objects.get(pk = id)
        # Primero eliminar la foto y despues el usuario
        ruta_foto = str(BASE_DIR) + str(a.foto.url)
        #averiguamos si la ruta es validad
        if path.exists(ruta_foto):
            #Borramos la ruta de la foto
            if a.foto.url != "/uploads/vitario/fotos/defaultUsu.png":
                remove(ruta_foto)
            # messages.success(request,"Foto eliminada correctamente")
        else:
            messages.error(request,"No se pudo eliminar la foto")
            raise Exception("Error!!! la foto no existe o no se encuentra")
        a.delete()
        messages.success(request,"Usuario eliminado correctamente")
        return redirect('vitario:usuario')
    except Usuario.DoesNotExist:

Pagina_Vitario/Vitario/templates/Vitario/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Tienda,Mascotas,Accesorios">
    <meta name="descriptions" content="Venta de accesorios para mascotas y atencion medica">
    <meta name="author" content="Juan Camilo Galeano">
    <link rel="stylesheet" href="{% static 'Vitario/css/style.css'%}">
    <link rel="stylesheet" href="{% static 'Vitario/css/index.css'%}">
    <link rel="stylesheet" href="{% static 'Vitario/css/login.css'%}">
    <link rel="stylesheet" href="{% static 'Vitario/css/form.css'%}">
    <link rel="stylesheet" href="{% static 'Vitario/css/tarjeta.css'%}">
    <link rel="stylesheet" href="{% static 'Vitario/css/apartar_cita.css'%}">
    {% comment %} Bootstrap 5.2 {% endcomment %}
    <link rel="stylesheet" href="{% static 'Vitario/bootstrap-icons-1.9.1/bootstrap-icons.css'%}">
    {% comment %} Bootstrap 5.2 {% endcomment %}
    <link rel="stylesheet" href="{% static 'Vitario/css/bootstrap.min.css'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'vitario/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'Vitario/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'Vitario/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'Vitario/favicon_io/site.webmanifest'  %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gideon+Roman&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <title>Vitario</title>
</head>
<body>
    <div id="img2">

        <a href="{% url 'Vitario:inicio' %}">
        <img src="{% static 'Vitario/img/logo.svg' %}" width="300" alt="logo vitario">
        </a>
        {% if request.session.logueo %}
        <div id="perro">
            <a class="nav-link" href="{% url 'Vitario:perfil' %}">
                <button type="button" class="btn btn-outline-secondary">Perfil <i class="bi bi-person-fill"></i></button>
            </a>
        </div>
        {% else %}

        {% endif %}
        <div id="perro">
            <a class="nav-link" href="{% url 'Vitario:carrito' %}">
                <button type="button" class="btn btn-outline-secondary">Carrito <i class="bi bi-cart3"></i></button>
            </a>
        </div>
    </div>
    <nav class="navbar navbar-expand-sm  navbar-light">
    
        <ul class="navbar-nav">
            {% if request.session.logueo.3 != "C" %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Vitario:inicio' %}"> Inicio </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Vitario:tarjetaservicio' %}">
            Servicios
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Productos
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'Vitario:accesorio' %}">Accesorios</a>
                <a class="dropdown-item" href="{% url 'Vitario:medicamento' %}">Medicamentos</a>
                <a class="dropdown-item" href="{% url 'Vitario:concentrado' %}">Concentrado</a>
                <a class="dropdown-item" href="{% url 'Vitario:premio' %}">Alimentos y Premios</a>
            </div>
        </li>
        {% endif %}
        {% if request.session.logueo.3 == "Administrador" or request.session.logueo.3 == "Empleado" %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            Listar
            </a>
            <div class="dropdown-menu">
                {% if request.session.logueo.3 == "Administrador" %}
                <a class="dropdown-item" href="{% url 'Vitario:usuario' %}">Usuarios</a>
                <a class="dropdown-item" href="{% url 'Vitario:mascota' %}">Mascotas</a>
                <a class="dropdown-item" href="{% url 'Vitario:producto' %}">Productos</a>
                <!--<a class="dropdown-item" href="{% url 'Vitario:factura' %}">Facturas</a>-->
                <a class="dropdown-item" href="{% url 'Vitario:servicio' %}">Servicios</a>
                <a class="dropdown-item" href="{% url 'Vitario:cita' %}">Citas</a>
                {% endif %}
                {% if request.session.logueo.3 == "Empleado" %}
                <a class="dropdown-item" href="{% url 'Vitario:mascota' %}">Mascotas</a>
                <a class="dropdown-item" href="{% url 'Vitario:producto' %}">Productos</a>
                <a class="dropdown-item" href="{% url 'Vitario:servicio' %}">Servicios</a>
                {% endif %}
            </div>
        </li>
        {% endif %}
    

        {% if request.session.logueo %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Vitario:login_cerrar' %}">
            <button type="button" class="btn btn-outline-secondary">Cerrar Sesion</button>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Vitario:agendar' %}">
            <button type="button" class="btn btn-outline-secondary">Agenda</button>
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Vitario:Registro' %}">
            <button type="button" class="btn btn-outline-secondary">Registro</button>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'Vitario:loginForm' %}">
            <button type="button" class="btn btn-outline-secondary">Iniciar Sesion</button>
            </a>
        </li>
        {% endif %}
        </ul>
    </nav>
    </div>
    {% if messages %}
        {% for i in messages %}
            <div class="alert alert-{% if i.tags != 'error' %}{{ i.tags }}{% elif i.tags == 'error' %}danger{% endif %}"
            role="alert">{{i}}</div>
        {% endfor %}
    {% endif %}
    {% block body  %}

    
    {% endblock  %}
        <footer class="footer">
            <div class="text-center p-3">
                &copy; Copyright <strong><span>Vitario</span></strong>. Reservamos los derechos de autor <br>
                Designed by <a style="color: #F0D1E1;" href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </footer>
    {% comment %} Bootstrap 5.2 with Popper {% endcomment %}
    <script src="{% static 'Vitario/js/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'Vitario/js/js/jquery-3.6.1.min.js'%}"></script>
    <script src="{% static 'Vitario/js/js/funciones.js'%}"></script>
    
</body>
</html>

Pagina_Vitario/Vitario/templates/Vitario/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Tienda,Mascotas,Accesorios">
    <meta name="descriptions" content="Venta de accesorios para mascotas y atencion medica">
    <meta name="author" content="Juan Camilo Galeano">
    <link rel="stylesheet" href="{% static 'Vitario/css/estilo.css'%}">
    <link rel="stylesheet" href="{% static 'Vitario/css/index.css'%}">
    <link rel="stylesheet" href="{% static 'Vitario/css/login.css'%}">
    {% comment %} Bootstrap 5.2 {% endcomment %}
    <link rel="stylesheet" href="{% static 'Vitario/css/bootstrap.min.css'%}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'vitario/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'Vitario/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'Vitario/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'Vitario/favicon_io/site.webmanifest'  %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gideon+Roman&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <title>Vitario</title>
</head>
<body>
    {% if messages %}
        {% for i in messages %}
            <div class="alert alert-{% if i.tags != 'error' %}{{ i.tags }}{% elif i.tags == 'error' %}danger{% endif %}"
            role="alert">{{i}}</div>
        {% endfor %}
    {% endif %}
    {% block body  %}

    {% endblock  %}
    {% comment %} Bootstrap 5.2 with Popper {% endcomment %}
    <script src="{% static 'Vitario/js/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'Vitario/js/js/funciones.js'%}"></script>
    
</body>
</html>