Pagina_Vitario/Pagina_Vitario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('',include('Vitario.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Pagina_Vitario/Vitario/urls.py
from django.urls import path

from . import views

app_name = "Vitario"

urlpatterns = [
    path('', views.inicio, name="inicio"),

    path('loginForm/',views.loginForm, name="loginForm"),
    path('login/',views.login, name="login"),
    path('loginC/',views.loginC, name="login_cerrar"),
    
    path('usuario/', views.usuario, name="usuario"),
    path('crear_usuario/', views.usuarioFormulario, name="crear_usuario"),
    path('guardar_usuario/', views.usuarioGuardar, name="guardar_usuario"),
    path('eliminar_usuario/<int:id>',views.usuarioEliminar, name="eliminar_usuario"),
    path('editarusUario/<int:id>',views.editarUsuario, name="editar_usuario"),
    path('actualizarUsuario/',views.actualizarUsuario, name="actualizar_usuario"),
    path('BuscarUsuario/',views.usuarioBuscar, name="Buscar_usuario"),
    path('registro/',views.usuarioRegistro, name="Registro"),
    
    path('mascota/', views.mascota, name="mascota"),
    path('crear_mascota/', views.mascotaFormulario, name="crear_mascota"),
    path('guardar_mascota/', views.mascotaGuardar, name="guardar_mascota"),
    path('eliminar_mascota/<int:id>',views.mascotaEliminar, name="eliminar_mascota"),
    path('editarMascota/<int:id>',views.editarMascota, name="editar_mascota"),
    path('actualizarMascota/',views.actualizarMascota, name="actualizar_mascota"),
    path('BuscarMascota/',views.mascotaBuscar, name="Buscar_mascota"),
    
    path('producto/', views.producto, name="producto"),
    path('crear_producto/', views.productoFormulario, name="crear_producto"),
    path('guardar_producto/', views.productoGuardar, name="guardar_producto"),
    path('eliminar_producto/<int:id>',views.productoEliminar, name="eliminar_producto"),
    path('editarProducto/<int:id>',views.editarProducto, name="editar_producto"),
    path('actualizarProducto/',views.actualizarProducto, name="actualizar_producto"),
    path('BuscarProducto/',views.productoBuscar, name="Buscar_producto"),
    path('concentrado/', views.productoConcentrado, name="concentrado"),
    path('accesorio/', views.productoAccesorio, name="accesorio"),
    path('medicamento/', views.productoMedicamento, name="medicamento"),
    path('premio/', views.productoPremios, name="premio"),
    
    path('factura/', views.factura, name="factura"),
    path('crear_factura/', views.facturaFormulario, name="crear_factura"),
    path('guardar_factura/', views.facturaGuardar, name="guardar_factura"),
    path('eliminar_factura/<int:id>',views.facturaEliminar, name="eliminar_factura"),
    path('editarFactura/<int:id>',views.editarFactura, name="editar_factura"),
    path('actualizarFactura/',views.actualizarFactura, name="actualizar_factura"),
    path('BuscarFactura/',views.facturaBuscar, name="Buscar_factura"),
    
    path('servicio/', views.servicio, name="servicio"),
    path('crear_servicio/', views.servicioFormulario, name="crear_servicio"),
    path('guardar_servicio/', views.servicioGuardar, name="guardar_servicio"),
    path('eliminar_servicio/<int:id>',views.servicioEliminar, name="eliminar_servicio"),
    path('editarServicio/<int:id>',views.editarServicio, name="editar_servicio"),
    path('actualizarServicio/',views.actualizarServicio, name="actualizar_servicio"),
    path('BuscarServicio/',views.servicioBuscar, name="Buscar_servicio"),
    path('tarjeta_servicio/', views.servicioTarjetas, name="tarjetaservicio"),
    
    path('cita/', views.cita, name="cita"),
    path('crear_cita/', views.citaFormulario, name="crear_cita"),
    path('guardar_cita/', views.citaGuardar, name="guardar_cita"),
    path('eliminar_cita/<int:id>',views.citaEliminar, name="eliminar_cita"),
    path('editarCita/<int:id>',views.editarCita, name="editar_cita"),
    path('actualizarCita/',views.actualizarCita, name="actualizar_cita"),
    path('BuscarCita/',views.citaBuscar, name="Buscar_cita"),
    path('agendar/', views.Agendar, name="agendar"),
    path('veragenda/<str:fecha>/', views.verAgenda, name="veragenda"),
    path('guardaragenda/<str:fecha>/', views.guardarAgenda, name="guardaragenda"),
    path('apartarCita/', views.apartarCita, name="apartarCita"),
    path('formularioApartarCita/<int:empleado>', views.formularioApartarCitas, name="formularioApartarCita"),
    
    path('perfil/',views.perfil, name="perfil"),
    path('actualizarPerfil/',views.actualizarPerfil, name="actualizar_perfil"),
    
    path('carrito/',views.carritoCompra, name="carrito"),
    path('agregar/<int:producto_id>/',views.agregar_producto, name="agregar"),
    path('restar/<int:producto_id>/',views.restar_producto, name="restar"),
    path('limpiar/',views.limpiar_carrito, name="limpiar"),
]

Pagina_Vitario/Vitario/views.py
from pathlib import Path
from django.shortcuts import render,redirect

from Vitario.Carrito import Carrito
from .models import Usuario, Mascota, Producto, Factura, Servicios, Citas, Disponibilidad
from django.core.paginator import Paginator
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.core.files.storage import FileSystemStorage
from datetime import datetime
from .crypt_1 import claveEncriptada
from os import remove, path
BASE_DIR = Path(__file__).resolve().parent.parent

# Create your views here.
#===================================================Perfil==============================================================

"""Obtiene la identificación del usuario de la sesión, luego obtiene los datos del usuario de la base
de datos y luego los pasa a la plantilla
    :param request: El objeto de la solicitud
    :return: El perfil del usuario.
"""
def perfil(request):

    login = request.session.get('logueo', False)
    q =Usuario.objects.get(pk = login[0])
    contexto = {"perfil": q }
    return render(request,'Vitario/usuario/perfil.html',contexto)

"""Actualiza el perfil del usuario.
    :param request: El objeto de la solicitud
    :return: una redirección a la vista de perfil.
"""

def actualizarPerfil(request):

    if request.method == "POST":
        try:
            # Obtener los datos del usuario de la base de datos y actualizarlos.
            login = request.session.get('logueo', False)

            q = Usuario.objects.get(pk = login[0])

            q.nombre = request.POST["nombre"]
            q.direccion = request.POST["direccion"]
            q.telefono = request.POST["telefono"]
            q.correo = request.POST["correo"]

            if q.usuario != request.POST["usuario"]:
                try:
                    consulta = Usuario.objects.get(usuario = request.POST["usuario"])
                    raise Exception("El usuario ya existe")
                except Usuario.DoesNotExist:
                    q.usuario = request.POST["usuario"]
            else:
                q.usuario = request.POST["usuario"]

            if request.POST["clave"] != "":
                q.clave = claveEncriptada(request.POST["clave"])

            q.save()
            login[1] = q.nombre
            request.session["logueo"] = login

            messages.success(request,"Actualizacion correcta")
        except Usuario.DoesNotExist:
            messages.error(request,'No existe el usuario')
        except Exception as e:
            messages.error(request, f"Error: {e}")
    else:
        messages.warning(request, "No envio datos...")

    return redirect('Vitario:perfil')

#=======================================================================================================================

"""Toma una solicitud y devuelve una respuesta.
    :param request: El objeto de solicitud es un objeto HttpRequest.
    :return: La función de renderizado está siendo devuelta.
"""

def inicio(request):
    return render(request, 'Vitario/index.html')

#====================================================LOGIN==============================================================

def loginForm(request):
    return render(request,'Vitario/login/login.html')

"""En esta funcion nos permite saber i el usuario existe y si existe que inicie sesión y rediríjalo a la página de 
inicio. y si no existe rediríjalos a la página de inicio de sesión.   
    :param request: El objeto de la solicitud
    :return: El usuario está siendo devuelto.
"""

def login(request):
        
    try:
        
        user = request.POST['usuario']
        pasw = claveEncriptada(request.POST["clave"])

        q = Usuario.objects.get(usuario = user, clave = pasw)
        
        request.session["logueo"] = [q.id, q.nombre, q.rol, q.get_rol_display()]
        messages.success(request,"Bienvenido!!")
        return redirect('Vitario:inicio')
    except:
        messages.warning(request,"Hay que ingresar los datos")
        return redirect('Vitario:inicio')   

"""Esta funcion elimina la variable de sesión "Cierra la sesión" y redirige a la página de inicio
    :param request: El objeto de la solicitud
    :return: la función de redirección.
"""

def loginC(request):

    try:
        del request.session["logueo"]
        messages.success(request, "Session cerrada")
    except Exception as e:
        messages.warning(request, "Ocurrio un error: ", e)
    return redirect('Vitario:inicio')

#=======================================================================================================================

# ===============================================USUARIOS===============================================================

"""Esta funcion consulta si el usuario ha iniciado sesión y es administrador o empleado y que muestre la lista 
de usuarios. Si el usuario no ha iniciado sesión o no es administrador o empleado, se le redirige a la página de inicio 
de sesión.
    :param request: El objeto de la solicitud
    :return:un objeto de renderizado.
"""

def usuario(request):
    
    login = request.session.get('logueo',False)
    if login and (login[3] == "Administrador" or login[3] == "Empleado"):
        q = Usuario.objects.all()
        
        p = Paginator(q, 9)
        p_number = request.GET.get('page')
        
        q = p.get_page(p_number)
        
        contexto = {'page_obj': q}
        
        return render(request, 'Vitario/usuario/listar_usuario.html', contexto)

    else:
        if login and login[3] != "Administrador" and login[3] != "Empleado":
            messages.warning(request, "usted no esta autorizados para este modulo")
            return redirect('Vitario:inicio')
        else:    
            messages.warning(request, "No has iniciado session")
            return redirect('Vitario:loginForm')

"""Si la solicitud es una solicitud POST, filtre el modelo Usuario por el término de búsqueda, pagine
    los resultados y represente los resultados en una plantilla
    
    :param request: El objeto de la solicitud
    :return: una representación de la plantilla 'Vitary/users/list_users_ajax.html'
"""
def usuarioBuscar (request):
    
    if request.method == "POST":
        q = Usuario.objects.filter(
            Q(nombre__icontains = request.POST["buscar"])|
            Q(usuario__icontains = request.POST["buscar"])
            )
        p = Paginator(q, 9)
        p_number = request.GET.get('page')
        
        q = p.get_page(p_number)
        
        contexto = {'page_obj': q, 'Datos': request.POST["buscar"]}
        
        return render(request, 'Vitario/usuario/listar_usuario_ajax.html',contexto)
    else:
        messages.warning(request, "No se han enviado datos")
        return redirect('Vitario:usuario')
    
"""Representa la plantilla y la devuelve
    :param request: El objeto de la solicitud
    :return: La función de renderizado está siendo devuelta.
"""
def usuarioFormulario(request):
    return render(request, 'Vitario/usuario/crear_usuario.html')

"""Si el método de solicitud es POST, guarde el archivo en el servidor; de lo contrario, establezca el
    archivo en la imagen predeterminada
    :param request: El objeto de la solicitud
    :return: una redirección a la url Vitario:usuario.
"""
def usuarioGuardar(request):
    try:
        if request.method == "POST":
                # Guardando la imagen en el servidor.
            if request.FILES:
                # crear instacian de file sistem storage
                fss = FileSystemStorage()
                # capturar foto de formulario
                r = request.FILES["foto"]
                # cargar archivo alservidor
                file = fss.save("vitario/fotos/"+ r.name, r)
            else:
                file = "vitario/fotos/defaultUsu.png"
            
            q = Usuario(
                nombre = request.POST["nombre"],
                direccion = request.POST["direccion"],
                telefono = request.POST["telefono"],
                correo = request.POST["correo"],
                usuario = request.POST["usuario"],
                clave = claveEncriptada(request.POST["clave"]),
                rol = request.POST["rol"],
                foto = file
            )
            q.save()
            messages.success(request,"¡Usuario guardado correctamente!")
            return redirect('Vitario:usuario')
        else:
            messages.warning(request, "¡No se han enviado datos!")
            return redirect('Vitario:usuario')
    except Exception as e:
        messages.error(request,"Error" + str(e))
        return redirect('Vitario:usuario')
    
"""Elimina un usuario de la base de datos y elimina la foto del usuario del servidor
    :param request: El objeto de la solicitud
    :param id: El id del objeto que se va a eliminar
    :return: una redirección a la url vitarium:usuario.
"""
def usuarioEliminar(request,id):
    try:
        a = Usuario.objects.get(pk = id)
        # Primero eliminar la foto y despues el usuario
        ruta_foto = str(BASE_DIR) + str(a.foto.url)
        #averiguamos si la ruta es validad
        if path.exists(ruta_foto):
            #Borramos la ruta de la foto
            if a.foto.url != "/uploads/vitario/fotos/defaultUsu.png":
                remove(ruta_foto)
            # messages.success(request,"Foto eliminada correctamente")
        else:
            messages.error(request,"No se pudo eliminar la foto")
            raise Exception("Error!!! la foto no existe o no se encuentra")
        a.delete()
        messages.success(request,"Usuario eliminado correctamente")
        return redirect('vitario:usuario')
    except Usuario.DoesNotExist:

Pagina_Vitario/Vitario/templates/Vitario/cita/apartar_cita.html
{% extends 'Vitario/base.html' %}

{% block body %}


<h2>Seleccione un empleado para tu cita</h2>

<div id="tabla">
    {% if datos %}
        {% for i in datos %}
            <div class="card" id="empleado">
                <h1 class="card-title">{{ i.nombre }}</h1>
                <img id="img-card" src="{{ i.foto.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ i.nombre }}</h5>
                    <a href="{% url 'Vitario:formularioApartarCita' i.id %}" class="btn btn-warning">Seleccionar</a>
                    <br>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h1>No hay datos</h1>
    {% endif %}
</div><br>
{% endblock %}

Pagina_Vitario/Vitario/templates/Vitario/cita/crear_cita.html
{% extends 'Vitario/base.html' %}

{% block body %}

<div class="signup-form">
    <form  action="{% url 'Vitario:guardar_cita' %}" method="post">
        {% csrf_token %}
        <h2>CREAR CITA</h2>
        <div class="form-group">
            <label for="">Usuario</label><br />
            <select class="form-control" name="nombre" required="required">
                {% if user %}
                    {% for registro in user %}
                        <option value="{{registro.id}}">{{registro.nombre}}</option>
                    {% endfor %}
                {% else %}
                    <h1>No hay datos</h1>
                {% endif %}
            </select>
        </div>
        <div class="form-group">
            <label for="">Hora y Fecha</label><br />
            <input type="datetime-local" class="form-control" name="hora_fecha" placeholder="Hora y Fecha" required="required">
        </div>
        <div class="form-group">
            <label for="">Servicio</label><br />
            <select class="form-control" name="nombre_servicio" required="required">
                {% if datos %}
                    {% for registro in datos %}
                        <option value="{{registro.id}}">{{registro.nombre_servicio}}</option>
                    {% endfor %}
                {% else %}
                    <h1>No hay datos</h1>
                {% endif %}
            </select>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-secondary">Guardar</button>
        </div>
    </form>
</div>
{% endblock  %}

Pagina_Vitario/Vitario/templates/Vitario/cita/editar_cita.html
{% extends 'Vitario/base.html' %}

{% block body %}

<h1>MODIFICAR CITAS <strong> -_- {{ datos.id_cita }} -_-</strong></h1>

<form style="text-align:center;" action="{% url 'Vitario:actualizar_cita' %}" method="post">
    {% csrf_token %}

    <input type="hidden" name="id" value="{{datos.id}}" >

    <label for="">Hora y fecha</label><br />
    <input type="datetime-local" class="form-control" name="hora_fecha" style="width:70%; margin-left: auto; margin-right:auto;" value="{{ datos.hora_fecha }}"><br/>

    <!-- <label for="">Servicio</label><br />
    <select class="form-control" name="nombre_servicio" style="width:70%; margin-left: auto; margin-right:auto;" value="{{ datos.nombre_servicio }}">
        {% if servi %}
            {% for registro in servi %}
                <option value="{{registro.id}}">{{registro.nombre_servicio}}</option>
            {% endfor %}
        {% else %}
            <h1>No hay datos</h1>
        {% endif %}
    </select><br/> -->

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock  %}

Pagina_Vitario/Vitario/templates/Vitario/cita/listar.html
{% extends 'Vitario/base.html' %}

{% block body %}

<h1>AGENDAS</h1>


{% if datos %}

    <table class="table">
        <thead>
            <tr>
                <td>Fecha Inicio</td>
                <td colspan="2">Operaciones</td>
            </tr>
        </thead>
        <tbody>
            {% for registro in datos %}
            <tr>
                <td>{{ registro.fecha_inicio }}</td>
                <td>
                    <a class="btn btn-warning" href="{% url 'Vitario:veragenda' registro.fecha_inicio %}">Ver</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


{% else %}
    <h1>No hay Agendas</h1>
{% endif %}

</div>

{% endblock %}

Pagina_Vitario/Vitario/templates/Vitario/cita/listar_cita.html
{% extends 'Vitario/base.html' %}


{% block body %}

<h1>CITAS</h1>

<a class="btn btn-primary" href="{% url 'Vitario:crear_cita' %}">Nueva cita</a> <br /><br />

    
    <input class="form-control me-2" type="search" name="buscar" id="buscar" placeholder="Buscar" aria-label="Search" value="{{ Datos }}" onkeyup="buscarA('{% url 'Vitario:Buscar_cita' %}');">
    {% csrf_token %}

{%  if Datos %}
<a href="{% url 'Vitario:cita' %}"> ver todos </a>
{% endif %}

<div id="res">

{% if page_obj %}




<table border="1" width="100%" class="table">
    <thead>
        <tr>  
            <td>Id</td>
            <td>Usuario</td>
            <td>Hora y fecha</td>
            <td>Servicio</td>
            <td>Editar</td>
            <td>Eliminar</td>
        </tr>
    </thead>
    <tbody>

        {% for registro in page_obj %}
        <tr>
            <td>{{ registro.id }}</td>
            <td>{{ registro.usuario }}</td>
            <td>{{ registro.hora_fecha }}</td>
            <td>{{ registro.servicio }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'Vitario:editar_cita' registro.id %}"> editar</a>
            </td>
            <td>
                <a class="btn btn-danger" onclick="confirmarEliminar('{% url 'Vitario:eliminar_cita' registro.id %}')";> eliminar</a>
            </td>
        </tr>
        

        {% endfor %}
    </tbody>
</table>

<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
            
            <a class="page-link" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }} " {% endif %}  >Anterior</a>
            
        </li>
        {% for i in "d"|rjust:page_obj.paginator.num_pages|make_list %}

        <li class="page-item {% if forloop.counter == page_obj.number %} active {% endif %}"><a class="page-link" aria-current="page " href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>

        {% endfor %}

        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %} ">
            <a class="page-link" {% if page_obj.has_next %} href="?page={{ page_obj.next_page_number }}" {% endif %} >siguiente</a>
        </li>
    </ul>
</nav>



{% else %}
<h1>No hay datos</h1>
{% endif %}

</div>

{% endblock %}

Pagina_Vitario/Vitario/templates/Vitario/cita/listar_cita_ajax.html
{% if page_obj %}



<table border="1" width="100%" class="table">
    <thead>
        <tr>
            <td>ID</td>
            <td>Usuario</td>
            <td>Hora y fecha</td>
            <td>Servicio</td>
            <td>Editar</td>
            <td>Eliminar</td>
        </tr>
    </thead>
    <tbody>

        {% for registro in page_obj %}
        <tr>
            <td>{{ registro.id }}</td>
            <td>{{ registro.nombre }}</td>
            <td>{{ registro.hora_fecha }}</td>
            <td>{{ registro.servicio }}</td>
            <td>
                <a class="btn btn-primary" href="{% url 'Vitario:editar_cita' registro.id %}"> editar</a>
            </td>
            <td>
                <a class="btn btn-danger" onclick="confirmarEliminar('{% url 'Vitario:eliminar_cita' registro.id %}')";> eliminar</a>
            </td>
        </tr>
        

        {% endfor %}
    </tbody>
</table>

<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
            
            <a class="page-link" {% if page_obj.has_previous %} href="?page={{ page_obj.previous_page_number }} " {% endif %}  >Anterior</a>
            
        </li>
        {% for i in "d"|rjust:page_obj.paginator.num_pages|make_list %}

        <li class="page-item {% if forloop.counter == page_obj.number %} active {% endif %}"><a class="page-link" aria-current="page " href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>

        {% endfor %}

        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %} ">
            <a class="page-link" {% if page_obj.has_next %} href="?page={{ page_obj.next_page_number }}" {% endif %} >siguiente</a>
        </li>
    </ul>
</nav>



{% else %}
<h1>No hay datos</h1>
{% endif %}